# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/riley/Documents/prgms/c++/FirstSFMLGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/riley/Documents/prgms/c++/FirstSFMLGame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/riley/Documents/prgms/c++/FirstSFMLGame/CMakeFiles /home/riley/Documents/prgms/c++/FirstSFMLGame/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/riley/Documents/prgms/c++/FirstSFMLGame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Violet

# Build rule for target.
Violet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Violet
.PHONY : Violet

# fast build rule for target.
Violet/fast:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/build
.PHONY : Violet/fast

src/Coin.o: src/Coin.cpp.o

.PHONY : src/Coin.o

# target to build an object file
src/Coin.cpp.o:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Coin.cpp.o
.PHONY : src/Coin.cpp.o

src/Coin.i: src/Coin.cpp.i

.PHONY : src/Coin.i

# target to preprocess a source file
src/Coin.cpp.i:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Coin.cpp.i
.PHONY : src/Coin.cpp.i

src/Coin.s: src/Coin.cpp.s

.PHONY : src/Coin.s

# target to generate assembly for a file
src/Coin.cpp.s:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Coin.cpp.s
.PHONY : src/Coin.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Renderable.o: src/Renderable.cpp.o

.PHONY : src/Renderable.o

# target to build an object file
src/Renderable.cpp.o:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Renderable.cpp.o
.PHONY : src/Renderable.cpp.o

src/Renderable.i: src/Renderable.cpp.i

.PHONY : src/Renderable.i

# target to preprocess a source file
src/Renderable.cpp.i:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Renderable.cpp.i
.PHONY : src/Renderable.cpp.i

src/Renderable.s: src/Renderable.cpp.s

.PHONY : src/Renderable.s

# target to generate assembly for a file
src/Renderable.cpp.s:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Renderable.cpp.s
.PHONY : src/Renderable.cpp.s

src/Tile.o: src/Tile.cpp.o

.PHONY : src/Tile.o

# target to build an object file
src/Tile.cpp.o:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Tile.cpp.o
.PHONY : src/Tile.cpp.o

src/Tile.i: src/Tile.cpp.i

.PHONY : src/Tile.i

# target to preprocess a source file
src/Tile.cpp.i:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Tile.cpp.i
.PHONY : src/Tile.cpp.i

src/Tile.s: src/Tile.cpp.s

.PHONY : src/Tile.s

# target to generate assembly for a file
src/Tile.cpp.s:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Tile.cpp.s
.PHONY : src/Tile.cpp.s

src/Utility.o: src/Utility.cpp.o

.PHONY : src/Utility.o

# target to build an object file
src/Utility.cpp.o:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Utility.cpp.o
.PHONY : src/Utility.cpp.o

src/Utility.i: src/Utility.cpp.i

.PHONY : src/Utility.i

# target to preprocess a source file
src/Utility.cpp.i:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Utility.cpp.i
.PHONY : src/Utility.cpp.i

src/Utility.s: src/Utility.cpp.s

.PHONY : src/Utility.s

# target to generate assembly for a file
src/Utility.cpp.s:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/Utility.cpp.s
.PHONY : src/Utility.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Violet.dir/build.make CMakeFiles/Violet.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Violet"
	@echo "... edit_cache"
	@echo "... src/Coin.o"
	@echo "... src/Coin.i"
	@echo "... src/Coin.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Renderable.o"
	@echo "... src/Renderable.i"
	@echo "... src/Renderable.s"
	@echo "... src/Tile.o"
	@echo "... src/Tile.i"
	@echo "... src/Tile.s"
	@echo "... src/Utility.o"
	@echo "... src/Utility.i"
	@echo "... src/Utility.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

